CREATE TABLE IF NOT EXISTS events (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  location VARCHAR(255) NOT NULL,
  event_time DATETIME NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price VARCHAR(10) NOT NULL,
  imageURL VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);